### ISSUE TITLE
Alle Links verknüpfen

### ISSUE THREAD

**Issue by danielmoessner** [danielmoessner/katharina-greuner.de#22]
- [x] Alle Links verknüpfen. Es soll auf keiner Seite mehr einen Link oder Button geben der ins nichts führt.
- [x] Im Footer Mein Angebot und Info mit Links füllen

**Comment by towezo** [comment]
Die Kachel "Supervision" leitet vorerst auf keine Seite weiter.

**Comment by towezo** [comment]
kala - heilarbeit : buttons zur kontaktaufnahme führen auf die selbe Seite 
ausbildung : buttons zur kontaktaufnahme führen auf die selbe Seite 
yoga : "anfragen & termin"-Button führt auf die selbe seite
heilsame-seminare: "so erreichst du mich"- Button führt auf die selbe seite
