### ISSUE TITLE
Mobilanpassung

### ISSUE THREAD

**Issue by danielmoessner** [danielmoessner/katharina-greuner.de#23]
- [x] Alle Seiten auf mobile Version überprüfen und testen dass es funktioniert.
- [x] Falls eine Seite nicht angepasst ist, entweder anpassen oder hier als Kommentar hinzufügen.

**Comment by towezo** [comment]
auf der "Über mich"-Seite sieht der untere Teil nicht so gut aus, wegen dem conditional rendering.

Der Fehler befindet sich in der "SectionAboutBlocks.tsx" Component.

Ich habe ein Kommentar an besagter stelle hinterlassen.
