### ISSUE TITLE
Über mich Seite im CMS den kompletten Lebenslauf eingeben

### ISSUE THREAD

**Issue by danielmoessner** [danielmoessner/katharina-greuner.de#29]
Vorlage ist [hier zu finden](https://github.com/danielmoessner/katharina-greuner.de/blob/main/other/02_ueber_mich/katharina_uebermich_ausklapptexte.pdf)

- [x] Den Lebenslauf ab 1990-1993, also da wo er fehlt in das CMS eingeben unter Sektion Berufsweg > Lebenslauf
- [x] Ausbildungen und Fortbildungen eingegeben
- [x] Beruflicher Werdegang eingegeben

**Comment by towezo** [comment]
inhaltsverzeichnis im CMS ausgefüllt, wird noch nicht angezeigt, muss wohl noch in der SectionAboutBlocks.tsx ergänzt werden.
